### ISSUE TITLE
Cannot find name 'google'.

### ISSUE THREAD

**Issue by faizy-ahmed** [doing007/ionic-3-google-maps-autocomplete#1]
I have tried 'ionic serve' on windows 10 (x64) but getting the following error on browser:
`
Typescript Error
Cannot find name 'google'.
autocomplete-master/ionic-3-google-maps-autocomplete-master/src/pages/map/map.ts
loadMaps() {
  if (!!google) {
    this.initializeMap();
`

**Comment by doing007** [comment]
@faizy-ahmed please let me know whether you are trying to integrate this into your project or directly working on top of this repo.

It would be great If you can tell me the steps that you have followed.

**Comment by Saqib92** [comment]
I am directly working on your repo. (Thanks for this great work.).
but having problem on windows environment(switched 5 PC's). while working on Ubuntu didn't face any error and compiled successful.

**Comment by faizan-catalyst** [comment]
I am working **directly working on your repo** and facing this issue, the steps are as follows:
1) Download Zip Code.
2) Open cmd to the project path.
3) Run the command 'npm install'.
4) Run the command 'ionic serve'.
5) Browser giving the error mentioned on my last comment.
Note: I am using Windows 10 (x64).

Thanks in advance!

**Comment by faizy-ahmed** [comment]
I am working directly working on your repo and facing this issue, the steps are as follows:

Download Zip Code.
Open cmd to the project path.
Run the command 'npm install'.
Run the command 'ionic serve'.
Browser giving the error mentioned on my last comment.
Note: I am using Windows 10 (x64).
Thanks in advance!

**Comment by Saqib92** [comment]
![error](https://user-images.githubusercontent.com/7135885/42317524-05e31cf2-8066-11e8-98af-57eeb2a43162.jpg)
this is the error screenshot we are having.

**Comment by faizy-ahmed** [comment]
I resolved this issue by declaring a variable like **declare var google;** before **@IonicPage()** as shown in the picture.
![resolved](https://user-images.githubusercontent.com/10797092/42334838-dc2106ae-8097-11e8-8da1-f3ec77e08c51.png)
