### ISSUE TITLE
Navigation between 2 places. 

### ISSUE THREAD

**Issue by Saqib92** [doing007/ionic-3-google-maps-autocomplete#2]
Please Add navigation between 2 places. create route between places and calculate Distance. Thanks. 
P.S: I am working on it if i accomplish this i will let you know.

**Comment by doing007** [comment]
@Saqib92 I will work on this when I get time. But If you do it before I do, you can take my code and work on top of it. So that other people will use it.

**Comment by doing007** [comment]
I will do it by end of the day.

**Comment by doing007** [comment]
Hey @Saqib92 , I have created **dev** branch.
Please create new branch from **dev** and add your changes and name you branch with feature name

**Comment by Saqib92** [comment]
Okay Thanks. Working on it.

**Comment by Saqib92** [comment]
` startNavigating(){
 
        let directionsService = new google.maps.DirectionsService;
        let directionsDisplay = new google.maps.DirectionsRenderer;
 
        directionsDisplay.setMap(this.map);
       // directionsDisplay.setPanel(this.directionsPanel.nativeElement);
 
        directionsService.route({
            origin: 'Your Start Location',  // you can use lat, lng or formatted address
            destination: 'Your Destination location', // you can use lat, lng or formatted address
            travelMode: google.maps.TravelMode['DRIVING']
        }, (res, status) => {
 
            if(status == google.maps.DirectionsStatus.OK){
                directionsDisplay.setDirections(res);
            } else {
                console.warn(status);
            }
 
        });
 
    }`

**Comment by Saqib92** [comment]
Please Add this to your code. Thanks

**Comment by Saqib92** [comment]
please Add this to your Code.
